# Uncomment this line to define a global platform for your project
 platform :ios, '7.0'

target 'SandikSonuc' do
pod 'AFNetworking', '~> 2.0'
pod 'GoogleAnalytics-iOS-SDK'
end

target 'SandikSonucTests' do

end

